version: '3.5'

services:
  api01: &api
    hostname: api01
    build:
      context: .
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '200MB'

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"

  nginx:
    image: nginx:alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"

  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    ports:
      - "5433:5432"
    volumes:
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: 'postgres -c config_file=/etc/postgresql/postgresql.conf'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '140MB'

networks:
  default:
    driver: bridge
    name: rinha-nginx